spring:
  profiles:
    active: dev,robot,crypto,docs,desensitize,dict

server:
  servlet:
    context-path: /examples
    multipart:
      max-file-size: -1        # 单个文件大小限制
      max-request-size: -1     # 总请求大小限制
      enabled: true
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  port: 8080
  tomcat:
    max-http-form-post-size: -1
    max-swallow-size: -1
excel:
  thread-pool:
    max-parallelism: 10  # 最大并行度
  export:
    max-rows-per-sheet: 1000000  # 每个sheet最大行数
    max-sheets-per-file: 10     # 每个文件最大sheet数
    fetch-size: 100000          # 每次查询数据量，调大一些
    temp-dir: /home/temp/excel       # 临时目录
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

netty:
  websocket:
    port: 9081
    path: /chat
    auth-enabled: true  # 启用鉴权
    # 配置子协议
    #    subprotocols:
    #      - v1.protocol.example.com
    #      - v2.protocol.example.com
    # 其他配置
    boss-threads: 1
    worker-threads: 4
    max-frame-size: 65536
    session-timeout: 30m  # 30分钟
    cluster:
      enabled: true
      topic: ws:chat
      session-timeout: 1h  # 1小时
    heartbeat:
      enabled: true
      reader-idle-time: 60  # 60秒没收到数据就断开连接
      writer-idle-time: 30  # 30秒发送一次心跳包
    ssl:
      enabled: false
      # openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt
      cert-path: /Users/lin/home/code/github/common-tool/examples/src/main/resources/ssl/server.crt
      key-path: /Users/lin/home/code/github/common-tool/examples/src/main/resources/ssl/server.key
#      key-password: your-password
    server-options:
      so-backlog: 1024
    child-options:
      so-keepalive: true
      tcp-nodelay: true
      so-rcvbuf: 131072
      so-sndbuf: 131072
      options:
        WRITE_BUFFER_WATER_MARK_HIGH: 65536
        WRITE_BUFFER_WATER_MARK_LOW: 32768

logging:
  level:
    io.github.kk01001.netty: debug