netty:
  websocket:
    port: 9081
    path: /chat
    auth-enabled: true  # 启用鉴权
    # 配置子协议
    #    subprotocols:
    #      - v1.protocol.example.com
    #      - v2.protocol.example.com
    # 其他配置
    boss-threads: 1
    worker-threads: 4
    max-frame-size: 65536
    session-timeout: 30m  # 30分钟
    cluster:
      enabled: true
      topic: ws:chat
      session-timeout: 1h  # 1小时
      session-key-prefix: "netty-ws:session:"
      node-key-prefix: "netty-ws:node"
      broadcast-channel-prefix: "netty-ws:broadcast:"
      cleanup-interval: 5m  # 清理任务的间隔时间
      session-shard-count: 5  # 会话分片数量
    heartbeat:
      enabled: true
      reader-idle-time: 60  # 60秒没收到数据就断开连接
      writer-idle-time: 30  # 30秒发送一次心跳包
    ssl:
      enabled: false
      # openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt
      cert-path: /Users/lin/home/code/github/common-tool/examples/src/main/resources/ssl/server.crt
      key-path: /Users/lin/home/code/github/common-tool/examples/src/main/resources/ssl/server.key
    #      key-password: your-password
    server-options:
      so-backlog: 1024
    child-options:
      so-keepalive: true
      tcp-nodelay: true
      so-rcvbuf: 131072
      so-sndbuf: 131072
      options:
        WRITE_BUFFER_WATER_MARK_HIGH: 65536
        WRITE_BUFFER_WATER_MARK_LOW: 32768
